### ISSUE TITLE
[DISCUSSION] How the struct constants should be used with Leptos dynamic classes

### ISSUE THREAD

**Issue by SSeanin** [myFavShrimp/turf#14]
There is a problem with the using the Leptos dynamic classes with turf.
When using the dynamic classes with the following syntax for example
```html
<a class=ClassName::BTN class:(ClassName::BTN_CTA)=cta>
</a>
```
the `class:(ClassName::BTN_CTA)=cta` part will produce an error because of the `view` macro.

How can we use turf with Leptos dynamic classes?

**Comment by SSeanin** [comment]
I've also tried the bellow syntax of the dynamic classes
```html
<a class=ClassName::BTN class=(ClassName::BTN_CTA, cta)>
</a>
```
this will again produce an error because it expects a string literal by a struct field is passed.

**Comment by SSeanin** [comment]
I axed using of the Leptos `view!` macro for using the view builder syntax for now.

**Comment by SSeanin** [comment]
This can also be fixed using rust `Option<>` type and if expression rather than using the Leptos syntax of `class:ClassName::SOMETHING`.

**Comment by myFavShrimp** [comment]
I achieved similar behavior using a closure that returns the class name

```rust
let (count, set_count) = create_signal(0);

let my_class_name = move || {
    if count.get() % 2 == 0 {
        ClassName::SOME_CLASS
    } else {
        ""
    }
};

view! {
    <style>{STYLE_SHEET}</style>
    <div class=my_class_name>
    </div>
}
```
