### ISSUE TITLE
turf cant parse css svg noise paterns

### ISSUE THREAD

**Issue by klownie** [myFavShrimp/turf#25]
I'm sorry, but i cant provide context on why this is happening.
I noticed that  noise paterns in scss dont get parsed into css correctly.
for exemple:
https://jsfiddle.net/at5hwy2s/
It compiles but does not seem to apply the css correctly.
instead it gets turned into this :
https://jsfiddle.net/at5hwy2s/1/
wich does not work sadly.

**Comment by myFavShrimp** [comment]
Hey, this seems to be problem with the library you use for rendering your HTML. The symbols are HTML encoded. Many libraries do this by default to prevent accidental html/script injection into your site when displaying dynamic user content. 

There should be a setting for your library to tell it to render the html in a 'raw' unescaped way.
[Askama for example provides a `safe` filter](https://djc.github.io/askama/filters.html#safe) and for Leptos you can [insert raw html strings using the `inner_html` attribute on elements](https://docs.rs/leptos/latest/leptos/struct.HtmlElement.html#method.inner_html).

I hope this helps! As this is not a problem on turf's side I will close this issue. However, I will update turf's examples as they don't make it obvious that this is required so thank you for creating the issue!

**Comment by klownie** [comment]
thanks, sorry for the misunderstanding.
adding the safe filter fixed the issue in askama.
```
<style>
    {{ style_sheet|safe}}
</style>
```
