### ISSUE TITLE
CSS does not reload with cargo leptos watch

### ISSUE THREAD

**Issue by beckend** [myFavShrimp/turf#6]
Have to restart the command every time making a change in scss files.

**Comment by myFavShrimp** [comment]
Hey, thank you for reporting this issue. This problem seems to originate from the `cargo leptos` command. (https://github.com/leptos-rs/cargo-leptos/issues/187)

**Comment by myFavShrimp** [comment]
I am closing this because there is nothing turf can do to fix this
